/**
 * generateDiseases.js
 * Run: node scripts/generateDiseases.js
 * Output: assets/diseases.json  (1000+ entries)
 */

const fs = require('fs');
const path = require('path');

// ─── Seed data: 1000+ real disease names grouped by category ─────────────────

const SEED = {
  eyes: [
    'Conjunctivitis','Dry Eye Syndrome','Stye (Hordeolum)','Chalazion','Blepharitis',
    'Uveitis','Glaucoma','Cataracts','Macular Degeneration','Diabetic Retinopathy',
    'Retinal Detachment','Color Blindness','Amblyopia (Lazy Eye)','Strabismus',
    'Pterygium','Pinguecula','Corneal Ulcer','Keratitis','Iritis','Scleritis',
    'Episcleritis','Optic Neuritis','Orbital Cellulitis','Dacryocystitis',
    'Dacryostenosis','Entropion','Ectropion','Trichiasis','Xanthelasma',
    'Floaters and Flashes','Night Blindness','Photophobia','Nystagmus',
    'Presbyopia','Myopia','Hyperopia','Astigmatism','Subconjunctival Hemorrhage',
    'Chemical Eye Burn','Snow Blindness','Arc Eye (Welder\'s Flash)','Eye Strain',
    'Computer Vision Syndrome','Ocular Hypertension','Retinitis Pigmentosa',
    'Central Retinal Artery Occlusion','Central Retinal Vein Occlusion',
    'Vitreous Hemorrhage','Eyelid Dermatitis','Contact Lens Keratitis',
  ],
  teeth: [
    'Dental Caries (Tooth Decay)','Toothache','Gingivitis','Periodontitis',
    'Dental Abscess','Tooth Sensitivity','Bruxism (Teeth Grinding)','Dry Socket',
    'Impacted Wisdom Tooth','Mouth Ulcers (Aphthous Stomatitis)','Oral Thrush',
    'Leukoplakia','Oral Lichen Planus','Geographic Tongue','Black Hairy Tongue',
    'Glossitis','Stomatitis','Angular Cheilitis','Cheilitis','Halitosis',
    'Xerostomia (Dry Mouth)','Temporomandibular Joint Disorder (TMJ)',
    'Dental Fluorosis','Enamel Hypoplasia','Amelogenesis Imperfecta',
    'Dentinogenesis Imperfecta','Cracked Tooth Syndrome','Tooth Erosion',
    'Gum Recession','Pericoronitis','Necrotizing Ulcerative Gingivitis',
    'Salivary Gland Infection','Parotitis','Sialadenitis','Salivary Gland Stone',
    'Mucocele','Ranula','Epulis','Fibroma (Oral)','Papilloma (Oral)',
    'Torus Palatinus','Torus Mandibularis','Burning Mouth Syndrome',
    'Oral Submucous Fibrosis','Denture Stomatitis','Orthodontic Pain',
    'Pulpitis','Periapical Abscess','Hypercementosis',
  ],
  skin: [
    'Acne Vulgaris','Eczema (Atopic Dermatitis)','Psoriasis','Rosacea',
    'Seborrheic Dermatitis','Contact Dermatitis','Urticaria (Hives)',
    'Ringworm (Tinea Corporis)','Athlete\'s Foot (Tinea Pedis)',
    'Jock Itch (Tinea Cruris)','Tinea Versicolor','Onychomycosis (Nail Fungus)',
    'Impetigo','Cellulitis','Erysipelas','Folliculitis','Furuncle (Boil)',
    'Carbuncle','Hidradenitis Suppurativa','Pilonidal Cyst','Sebaceous Cyst',
    'Lipoma','Keloid','Hypertrophic Scar','Stretch Marks','Vitiligo',
    'Melasma','Freckles','Age Spots (Solar Lentigines)','Dermatofibroma',
    'Epidermoid Cyst','Milia','Syringoma','Xanthoma','Acanthosis Nigricans',
    'Keratosis Pilaris','Ichthyosis Vulgaris','Pityriasis Rosea',
    'Lichen Planus','Lichen Sclerosus','Granuloma Annulare','Erythema Multiforme',
    'Erythema Nodosum','Pemphigus Vulgaris','Bullous Pemphigoid',
    'Dermatitis Herpetiformis','Scabies','Lice (Pediculosis)','Bed Bug Bites',
    'Flea Bites','Mosquito Bite Reaction','Sunburn','Polymorphous Light Eruption',
    'Phototoxic Dermatitis','Drug Rash','Toxic Epidermal Necrolysis',
    'Stevens-Johnson Syndrome','Pityriasis Lichenoides','Purpura','Petechiae',
    'Ecchymosis','Hemangioma','Port Wine Stain','Cherry Angioma',
    'Spider Angioma','Pyogenic Granuloma','Warts (Verruca Vulgaris)',
    'Plantar Warts','Molluscum Contagiosum','Herpes Zoster (Shingles)',
    'Cold Sores (Herpes Simplex)','Hand Foot and Mouth Disease','Measles Rash',
    'Chickenpox','Scarlet Fever Rash','Rocky Mountain Spotted Fever',
    'Lyme Disease Rash','Intertrigo','Diaper Rash','Nummular Eczema',
    'Dyshidrotic Eczema','Neurodermatitis','Prurigo Nodularis',
    'Stasis Dermatitis','Lipodermatosclerosis','Pressure Ulcer',
    'Ingrown Toenail','Paronychia','Whitlow (Herpetic)','Corn and Callus',
    'Blister','Abrasion','Laceration','Puncture Wound',
    'Sebaceous Hyperplasia','Comedone','Miliaria (Heat Rash)',
    'Grover\'s Disease','Fox-Fordyce Disease','Darier\'s Disease',
  ],
  stomach: [
    'Gastroesophageal Reflux Disease (GERD)','Peptic Ulcer Disease',
    'Gastritis','Gastroparesis','Hiatal Hernia','Esophagitis',
    'Barrett\'s Esophagus','Dysphagia','Achalasia','Esophageal Spasm',
    'Gastroenteritis','Food Poisoning','Traveler\'s Diarrhea',
    'Irritable Bowel Syndrome (IBS)','Inflammatory Bowel Disease (IBD)',
    'Crohn\'s Disease','Ulcerative Colitis','Diverticulitis','Diverticulosis',
    'Appendicitis','Peritonitis','Intestinal Obstruction','Volvulus',
    'Intussusception','Inguinal Hernia','Umbilical Hernia','Celiac Disease',
    'Lactose Intolerance','Fructose Malabsorption','Small Intestinal Bacterial Overgrowth (SIBO)',
    'Constipation','Chronic Diarrhea','Fecal Impaction','Hemorrhoids',
    'Anal Fissure','Rectal Prolapse','Proctitis','Colitis',
    'Ischemic Colitis','Microscopic Colitis','Colonic Polyps',
    'Pancreatitis (Acute)','Pancreatitis (Chronic)','Pancreatic Insufficiency',
    'Liver Cirrhosis','Fatty Liver Disease (NAFLD)','Hepatitis A',
    'Hepatitis B','Hepatitis C','Autoimmune Hepatitis','Primary Biliary Cholangitis',
    'Cholecystitis','Cholelithiasis (Gallstones)','Cholangitis',
    'Primary Sclerosing Cholangitis','Biliary Dyskinesia',
    'Nausea and Vomiting','Cyclic Vomiting Syndrome','Bloating',
    'Functional Dyspepsia','Abdominal Adhesions','Mesenteric Lymphadenitis',
    'Whipple\'s Disease','Tropical Sprue','Protein-Losing Enteropathy',
    'Short Bowel Syndrome','Intestinal Pseudo-Obstruction',
    'Ogilvie Syndrome','Gastrointestinal Bleeding','Hematemesis',
    'Melena','Hematochezia','Angiodysplasia (GI)','Dieulafoy Lesion',
  ],
  fever: [
    'Influenza (Flu)','Common Cold','COVID-19','RSV Infection',
    'Mononucleosis (Mono)','Strep Throat','Tonsillitis','Pharyngitis',
    'Laryngitis','Scarlet Fever','Rheumatic Fever','Typhoid Fever',
    'Malaria','Dengue Fever','Chikungunya','Zika Virus Infection',
    'Yellow Fever','Ebola Virus Disease','Marburg Virus Disease',
    'Lassa Fever','West Nile Virus','Encephalitis (Viral)','Meningitis (Viral)',
    'Meningitis (Bacterial)','Sepsis','Bacteremia','Endocarditis',
    'Osteomyelitis','Pyelonephritis','Urinary Tract Infection',
    'Pneumonia (Bacterial)','Pneumonia (Viral)','Tuberculosis',
    'Pertussis (Whooping Cough)','Diphtheria','Mumps','Measles (Rubeola)',
    'Rubella','Chickenpox (Varicella)','Shingles (Herpes Zoster)',
    'Hand Foot and Mouth Disease','Roseola Infantum','Fifth Disease',
    'Kawasaki Disease','Rocky Mountain Spotted Fever','Lyme Disease',
    'Q Fever','Brucellosis','Leptospirosis','Rat-Bite Fever',
    'Rickettsia Infection','Typhus (Murine)','Typhus (Epidemic)',
    'Cat Scratch Disease','Toxoplasmosis','Cryptosporidiosis',
    'Giardiasis','Amoebiasis','Leishmaniasis','Trypanosomiasis',
    'Chagas Disease','Schistosomiasis','Filariasis','Ascariasis',
    'Hookworm Infection','Tapeworm Infection','Pinworm Infection',
    'Cellulitis with Fever','Erysipelas with Fever','Abscess (Systemic)',
    'Drug Fever','Heat Stroke','Heat Exhaustion','Fever of Unknown Origin',
    'Periodic Fever Syndrome','Familial Mediterranean Fever',
  ],
  injuries: [
    'Sprain (Ankle)','Sprain (Wrist)','Sprain (Knee)','Strain (Muscle)',
    'Strain (Hamstring)','Strain (Quadriceps)','Strain (Back)',
    'Fracture (Stress)','Fracture (Closed)','Fracture (Hairline)',
    'Dislocation (Shoulder)','Dislocation (Finger)','Dislocation (Knee)',
    'Contusion (Bruise)','Hematoma','Laceration','Abrasion',
    'Puncture Wound','Avulsion','Crush Injury','Degloving Injury',
    'Minor Burn (1st Degree)','Partial Burn (2nd Degree)','Sunburn',
    'Chemical Burn','Electrical Burn','Frostbite','Hypothermia',
    'Heat Cramps','Rhabdomyolysis','Compartment Syndrome',
    'Tendinitis (Achilles)','Tendinitis (Rotator Cuff)','Tendinitis (Patellar)',
    'Tennis Elbow (Lateral Epicondylitis)','Golfer\'s Elbow (Medial Epicondylitis)',
    'Carpal Tunnel Syndrome','Trigger Finger','De Quervain\'s Tenosynovitis',
    'Plantar Fasciitis','Shin Splints (MTSS)','Iliotibial Band Syndrome',
    'Runner\'s Knee (Patellofemoral Syndrome)','Bursitis (Hip)',
    'Bursitis (Shoulder)','Bursitis (Knee)','Meniscus Tear',
    'ACL Tear','Rotator Cuff Tear','Biceps Tendon Rupture',
    'Achilles Tendon Rupture','Concussion','Traumatic Brain Injury (Mild)',
    'Whiplash','Cervical Strain','Lumbar Strain','Sacroiliac Joint Sprain',
    'Rib Contusion','Rib Fracture','Clavicle Fracture','Nose Fracture',
    'Jaw Fracture','Finger Fracture','Wrist Fracture (Colles)','Ankle Fracture',
    'Toe Fracture','Ingrown Toenail (Traumatic)','Subungual Hematoma',
    'Eye Contusion','Corneal Abrasion','Foreign Body (Eye)',
    'Foreign Body (Ear)','Foreign Body (Nose)','Insect Sting Reaction',
    'Snake Bite','Spider Bite','Tick Bite','Jellyfish Sting',
    'Near Drowning','Decompression Sickness','Altitude Sickness',
  ],
  respiratory: [
    'Asthma','Chronic Obstructive Pulmonary Disease (COPD)','Emphysema',
    'Chronic Bronchitis','Acute Bronchitis','Bronchiolitis','Bronchiectasis',
    'Pneumonia (Community-Acquired)','Pneumonia (Hospital-Acquired)',
    'Aspiration Pneumonia','Pleuritis (Pleurisy)','Pleural Effusion',
    'Pneumothorax','Hemothorax','Pulmonary Embolism','Deep Vein Thrombosis',
    'Pulmonary Hypertension','Pulmonary Fibrosis','Idiopathic Pulmonary Fibrosis',
    'Sarcoidosis (Pulmonary)','Hypersensitivity Pneumonitis',
    'Occupational Asthma','Exercise-Induced Bronchoconstriction',
    'Acute Respiratory Distress Syndrome (ARDS)',
    'Respiratory Failure','Sleep Apnea (Obstructive)','Sleep Apnea (Central)',
    'Snoring','Croup','Epiglottitis','Laryngotracheobronchitis',
    'Tracheitis','Tracheomalacia','Vocal Cord Dysfunction',
    'Sinusitis (Acute)','Sinusitis (Chronic)','Rhinitis (Allergic)',
    'Rhinitis (Non-Allergic)','Nasal Polyps','Deviated Nasal Septum',
    'Epistaxis (Nosebleed)','Upper Respiratory Tract Infection',
    'Pertussis (Whooping Cough)','Tuberculosis (Pulmonary)',
    'Non-Tuberculous Mycobacterial Infection','Histoplasmosis',
    'Coccidioidomycosis','Aspergillosis','Pneumocystis Pneumonia',
    'Legionnaire\'s Disease','Q Fever (Pulmonary)','Anthrax (Pulmonary)',
    'Mesothelioma','Lung Cancer (NSCLC)','Lung Cancer (SCLC)',
    'Benign Lung Nodule','Hamartoma (Pulmonary)','Atelectasis',
    'Mucus Plugging','Dyspnea','Chronic Cough','Hemoptysis',
    'Cystic Fibrosis','Alpha-1 Antitrypsin Deficiency',
    'Pulmonary Alveolar Proteinosis','Lymphangioleiomyomatosis',
    'Good Pasture Syndrome','Wegener\'s Granulomatosis (GPA)',
    'Pleural Mesothelioma','Tracheal Stenosis','Vocal Cord Paralysis',
    'Laryngeal Cancer','Mediastinitis','Empyema (Pleural)','Lung Abscess',
    'Pulmonary Contusion','Diaphragmatic Hernia','Obesity Hypoventilation Syndrome',
    'High Altitude Pulmonary Edema','Pulmonary Edema','Respiratory Syncytial Virus',
    'Parainfluenza Virus Infection','Adenovirus Respiratory Infection',
    'Rhinovirus Infection','Metapneumovirus Infection',
  ],
  head: [
    'Tension Headache','Migraine','Cluster Headache','Trigeminal Neuralgia',
    'Occipital Neuralgia','Cervicogenic Headache','Sinus Headache',
    'Thunderclap Headache','Chronic Daily Headache','Hemicrania Continua',
    'New Daily Persistent Headache','Post-Concussion Headache',
    'Medication Overuse Headache','Idiopathic Intracranial Hypertension',
    'Temporal Arteritis (Giant Cell Arteritis)','Meningitis',
    'Encephalitis','Brain Abscess','Subdural Hematoma','Epidural Hematoma',
    'Subarachnoid Hemorrhage','Stroke (Ischemic)','TIA (Mini Stroke)',
    'Vertigo (BPPV)','Labyrinthitis','Vestibular Neuritis',
    'Meniere\'s Disease','Acoustic Neuroma','Tinnitus',
    'Sudden Sensorineural Hearing Loss','Conductive Hearing Loss',
    'Otitis Media (Acute)','Otitis Media (Chronic)','Otitis Media with Effusion',
    'Otitis Externa (Swimmer\'s Ear)','Malignant Otitis Externa',
    'Cholesteatoma','Otosclerosis','Perforated Eardrum',
    'Barotrauma (Ear)','Earwax Impaction','Mastoiditis',
    'Bell\'s Palsy','Ramsay Hunt Syndrome','Hemifacial Spasm',
    'Parotitis','Mumps','Temporal Mandibular Joint Disorder',
    'Otomycosis (Fungal Ear Infection)','Auricular Hematoma',
    'Superior Canal Dehiscence','Perilymphatic Fistula',
    'Auditory Processing Disorder','Hyperacusis','Misophonia',
    'Labyrinthine Concussion','Sudden Deafness',
    'Sinusitis (Frontal)','Sinusitis (Maxillary)','Sinusitis (Ethmoid)',
    'Allergic Rhinitis','Nasal Polyps','Anosmia','Hyposmia',
    'Dysgeusia','Taste Disorder','Facial Neuralgia',
    'Glossopharyngeal Neuralgia','Optic Neuritis','Papilledema',
    'Idiopathic Facial Pain','Dizziness','Presyncope','Syncope',
    'Ataxia (Cerebellar)','Nystagmus (Central)','Diplopia',
  ],
  bones: [
    'Osteoporosis','Osteopenia','Osteoarthritis','Rheumatoid Arthritis',
    'Psoriatic Arthritis','Ankylosing Spondylitis','Reactive Arthritis',
    'Gout','Pseudogout (CPPD)','Septic Arthritis','Osteomyelitis',
    'Paget\'s Disease of Bone','Osteonecrosis (Avascular Necrosis)',
    'Fibromyalgia','Polymyalgia Rheumatica','Giant Cell Arteritis',
    'Systemic Lupus Erythematosus (SLE)','Sjögren\'s Syndrome',
    'Scleroderma','Mixed Connective Tissue Disease','Polymyositis',
    'Dermatomyositis','Vasculitis','Spondylolisthesis','Scoliosis',
    'Kyphosis','Lordosis','Herniated Disc (Cervical)','Herniated Disc (Lumbar)',
    'Spinal Stenosis','Sciatica','Piriformis Syndrome','Sacroiliitis',
    'Coccydynia','Costochondritis','Tietze Syndrome','Fibrous Dysplasia',
    'Enchondroma','Osteochondroma','Chondromalacia Patella',
    'Patellofemoral Syndrome','Patellar Tendinopathy','Jumper\'s Knee',
    'Legg-Calvé-Perthes Disease','Slipped Capital Femoral Epiphysis',
    'Osgood-Schlatter Disease','Sever\'s Disease','Growing Pains',
    'Marfan Syndrome','Ehlers-Danlos Syndrome','Hypermobility Syndrome',
    'Reflex Sympathetic Dystrophy (CRPS)','Phantom Limb Pain',
    'Carpal Tunnel Syndrome','Cubital Tunnel Syndrome','Tarsal Tunnel Syndrome',
    'Dupuytren\'s Contracture','Ganglion Cyst','Baker\'s Cyst',
    'Flat Feet (Pes Planus)','High Arches (Pes Cavus)','Hallux Valgus (Bunion)',
    'Hammer Toe','Metatarsalgia','Morton\'s Neuroma','Heel Spur',
  ],
  heart: [
    'Hypertension (High Blood Pressure)','Hypotension (Low Blood Pressure)',
    'Coronary Artery Disease','Angina Pectoris','Myocardial Infarction (Heart Attack)',
    'Heart Failure (Systolic)','Heart Failure (Diastolic)','Cardiomyopathy (Dilated)',
    'Cardiomyopathy (Hypertrophic)','Cardiomyopathy (Restrictive)',
    'Atrial Fibrillation','Atrial Flutter','Supraventricular Tachycardia',
    'Ventricular Tachycardia','Ventricular Fibrillation','Bradycardia',
    'Heart Block (First Degree)','Heart Block (Second Degree)','Heart Block (Third Degree)',
    'Sick Sinus Syndrome','Wolff-Parkinson-White Syndrome','Long QT Syndrome',
    'Brugada Syndrome','Mitral Valve Prolapse','Mitral Stenosis',
    'Mitral Regurgitation','Aortic Stenosis','Aortic Regurgitation',
    'Tricuspid Regurgitation','Pulmonary Stenosis','Endocarditis (Infective)',
    'Pericarditis','Myocarditis','Cardiac Tamponade','Aortic Aneurysm',
    'Aortic Dissection','Peripheral Artery Disease','Raynaud\'s Phenomenon',
    'Thrombophlebitis','Varicose Veins','Chronic Venous Insufficiency',
    'Lymphedema','Hypercholesterolemia','Hypertriglyceridemia',
    'Metabolic Syndrome','Obesity','Obesity-Hypoventilation Syndrome',
    'Anemia (Iron Deficiency)','Anemia (B12 Deficiency)','Anemia (Folate)',
    'Hemolytic Anemia','Sickle Cell Anemia','Thalassemia',
    'Polycythemia Vera','Thrombocytopenia','Hemophilia',
    'Deep Vein Thrombosis','Pulmonary Embolism','Antiphospholipid Syndrome',
    'Von Willebrand Disease','Essential Thrombocythemia','Myelofibrosis',
    'Aplastic Anemia','Myelodysplastic Syndrome','Chronic Myeloid Leukemia',
    'Lymphoma (Hodgkin)','Lymphoma (Non-Hodgkin)','Multiple Myeloma',
    'Hypercoagulable State','Factor V Leiden Mutation','Protein C Deficiency',
    'Hereditary Hemochromatosis','Porphyria','Hypersplenism',
  ],
  mental: [
    'Depression (Major Depressive Disorder)','Persistent Depressive Disorder (Dysthymia)',
    'Bipolar Disorder Type I','Bipolar Disorder Type II','Cyclothymia',
    'Generalized Anxiety Disorder','Panic Disorder','Social Anxiety Disorder',
    'Specific Phobia','Agoraphobia','Separation Anxiety Disorder',
    'Obsessive-Compulsive Disorder (OCD)','Body Dysmorphic Disorder',
    'Hoarding Disorder','Trichotillomania','Excoriation Disorder',
    'Post-Traumatic Stress Disorder (PTSD)','Acute Stress Disorder',
    'Adjustment Disorder','Schizophrenia','Schizoaffective Disorder',
    'Delusional Disorder','Brief Psychotic Disorder','Schizophreniform Disorder',
    'Anorexia Nervosa','Bulimia Nervosa','Binge Eating Disorder',
    'Avoidant/Restrictive Food Intake Disorder','Pica','Rumination Disorder',
    'Attention-Deficit/Hyperactivity Disorder (ADHD)','Autism Spectrum Disorder',
    'Intellectual Disability','Specific Learning Disorder','Tourette Syndrome',
    'Insomnia Disorder','Hypersomnia','Narcolepsy','Restless Legs Syndrome',
    'Sleep Terror Disorder','Sleepwalking Disorder','REM Sleep Behavior Disorder',
    'Alcohol Use Disorder','Opioid Use Disorder','Cannabis Use Disorder',
    'Stimulant Use Disorder','Gambling Disorder','Internet Gaming Disorder',
    'Borderline Personality Disorder','Narcissistic Personality Disorder',
    'Antisocial Personality Disorder','Avoidant Personality Disorder',
    'Dependent Personality Disorder','Histrionic Personality Disorder',
    'Paranoid Personality Disorder','Schizoid Personality Disorder',
    'Dissociative Identity Disorder','Depersonalization-Derealization Disorder',
    'Dissociative Amnesia','Somatic Symptom Disorder','Illness Anxiety Disorder',
    'Functional Neurological Symptom Disorder','Factitious Disorder',
    'Grief and Bereavement','Burnout Syndrome','Seasonal Affective Disorder',
    'Reactive Attachment Disorder','Disinhibited Social Engagement Disorder',
    'Selective Mutism','Oppositional Defiant Disorder','Conduct Disorder',
    'Intermittent Explosive Disorder','Kleptomania','Pyromania',
    'Derealization Disorder','Depressive Psychosis','Catatonia',
  ],
  urinary: [
    'Urinary Tract Infection (UTI)','Cystitis','Pyelonephritis','Urethritis',
    'Interstitial Cystitis','Overactive Bladder','Urinary Incontinence (Stress)',
    'Urinary Incontinence (Urge)','Urinary Retention','Neurogenic Bladder',
    'Kidney Stones (Nephrolithiasis)','Hydronephrosis','Renal Colic',
    'Glomerulonephritis','Nephrotic Syndrome','Nephritic Syndrome',
    'IgA Nephropathy','Polycystic Kidney Disease','Chronic Kidney Disease',
    'Acute Kidney Injury','Renal Tubular Acidosis','Fanconi Syndrome',
    'Vesicoureteral Reflux','Ureteropelvic Junction Obstruction',
    'Retroperitoneal Fibrosis','Ureteral Stricture','Bladder Endometriosis',
    'Benign Prostatic Hyperplasia','Prostatitis (Acute Bacterial)',
    'Prostatitis (Chronic)','Epididymitis','Orchitis','Varicocele',
    'Hydrocele','Testicular Torsion','Phimosis','Paraphimosis',
    'Balanitis','Hematuria','Proteinuria','Pyuria','Nocturia','Dysuria',
    'Bedwetting (Enuresis)','Bladder Calculi','Urethral Stricture',
    'Vesicovaginal Fistula','Bladder Diverticulum',
    'Cystocele','Urethral Prolapse','Urethral Caruncle',
    'Renal Artery Stenosis','Renovascular Hypertension',
    'Alport Syndrome','Medullary Sponge Kidney',
    'Nephrocalcinosis','Renal Papillary Necrosis',
    'Obstructive Uropathy','Urinary Fistula','Bladder Neck Obstruction',
    'Urethral Diverticulum',
  ],
  womens: [
    'Dysmenorrhea (Painful Periods)','Amenorrhea (Primary)','Amenorrhea (Secondary)',
    'Menorrhagia (Heavy Periods)','Oligomenorrhea','Premenstrual Syndrome (PMS)',
    'Premenstrual Dysphoric Disorder (PMDD)','Endometriosis',
    'Polycystic Ovary Syndrome (PCOS)','Uterine Fibroids','Ovarian Cysts',
    'Ovarian Torsion','Pelvic Inflammatory Disease','Cervicitis','Vaginitis',
    'Bacterial Vaginosis','Vaginal Candidiasis (Thrush)','Trichomoniasis',
    'Vulvodynia','Vaginismus','Dyspareunia','Pelvic Organ Prolapse',
    'Stress Urinary Incontinence','Bartholin\'s Cyst','Vulvar Dermatitis',
    'Lichen Sclerosus (Vulvar)','Menopause Symptoms','Perimenopause',
    'Osteoporosis (Postmenopausal)','Mastitis','Breast Abscess',
    'Fibrocystic Breast Changes','Nipple Discharge','Galactorrhea',
    'Hyperprolactinemia','Premature Ovarian Insufficiency',
    'Gestational Diabetes','Hyperemesis Gravidarum','Preeclampsia',
    'Placenta Previa','Ectopic Pregnancy','Miscarriage','Postpartum Depression',
    'Postpartum Hemorrhage','Diastasis Recti',
    'Postnatal Anxiety','Postpartum Psychosis',
    'Pelvic Girdle Pain (Pregnancy)','Cervical Incompetence',
    'Placental Abruption','Ovarian Hyperstimulation Syndrome',
    'Asherman\'s Syndrome','Uterine Septum','Cervical Polyp',
    'Endometrial Polyp','Adenomyosis',
    'Vaginal Atrophy (Genitourinary Syndrome of Menopause)',
    'Pelvic Floor Dysfunction','Rectocele','Enterocele',
  ],
  childrens: [
    'Colic','Reflux in Infants','Nappy Rash','Cradle Cap (Seborrheic Dermatitis)',
    'Teething Pain','Febrile Seizures','Roseola Infantum','Fifth Disease (Slapped Cheek)',
    'Hand Foot and Mouth Disease','Chickenpox','Measles','Mumps','Rubella',
    'Whooping Cough (Pertussis)','Croup','Bronchiolitis (RSV)','Kawasaki Disease',
    'Intussusception','Pyloric Stenosis','Hirschsprung\'s Disease',
    'Necrotizing Enterocolitis','Meningitis (Childhood)','Encephalitis (Childhood)',
    'Cerebral Palsy','Developmental Delay','Autism Spectrum Disorder (Childhood)',
    'ADHD (Childhood)','Dyslexia','Dyscalculia','Enuresis (Bedwetting)',
    'Encopresis','Growth Hormone Deficiency','Precocious Puberty',
    'Delayed Puberty','Juvenile Idiopathic Arthritis','Duchenne Muscular Dystrophy',
    'Spina Bifida','Hydrocephalus','Down Syndrome','Turner Syndrome',
    'Klinefelter Syndrome','Phenylketonuria','Galactosemia',
    'Cystic Fibrosis (Childhood)','Sickle Cell Disease (Childhood)',
    'Thalassemia (Childhood)','Hemophilia (Childhood)','Idiopathic Thrombocytopenic Purpura',
    'Wilms Tumor','Neuroblastoma','Leukemia (Childhood ALL)',
    'Attention Issues in School','Sleep Problems in Children',
    'Juvenile Dermatomyositis','Neonatal Jaundice','Respiratory Distress Syndrome (Newborn)',
    'Transient Tachypnea of the Newborn','Neonatal Sepsis','Failure to Thrive',
    'Rickets','Scurvy (Childhood)','Kwashiorkor','Marasmus',
    'Fragile X Syndrome','Rett Syndrome','Prader-Willi Syndrome',
    'Angelman Syndrome','22q11 Deletion Syndrome','Williams Syndrome',
    'Noonan Syndrome','Congenital Heart Disease (ASD)','Congenital Heart Disease (VSD)',
    'Patent Ductus Arteriosus','Tetralogy of Fallot',
    'Congenital Hypothyroidism','Congenital Adrenal Hyperplasia',
    'G6PD Deficiency','Hereditary Spherocytosis',
  ],
};

// ─── Knowledge banks per category ────────────────────────────────────────────

const CAUSES = {
  eyes:      ['Bacterial infection','Viral infection','Allergic reaction','Environmental irritants','Prolonged screen use','Genetic predisposition','Autoimmune response','UV light exposure','Contact lens misuse','Age-related changes','Dry air or low humidity','Systemic disease (diabetes, hypertension)','Eye injury or trauma','Blocked tear duct','Eyelid abnormality'],
  teeth:     ['Poor oral hygiene','Plaque and tartar buildup','Bacterial infection','High-sugar diet','Dry mouth','Smoking or tobacco use','Hormonal changes','Vitamin deficiency','Grinding or clenching teeth','Poorly fitting dentures','Acid erosion','Genetic factors','Immune system dysfunction','Stress','Mouth breathing'],
  skin:      ['Bacterial infection','Fungal infection','Viral infection','Allergic reaction','Contact with irritants','Genetic predisposition','Autoimmune dysfunction','Hormonal imbalance','Excessive sweating','Poor hygiene','Nutritional deficiency','Stress or anxiety','Environmental triggers','Insect bites','Sun exposure'],
  stomach:   ['Bacterial infection (H. pylori, Salmonella)','Viral gastroenteritis','Food intolerance or allergy','Excessive alcohol consumption','Stress and anxiety','NSAIDs or medication side effects','Poor diet (high fat, low fibre)','Altered gut microbiome','Autoimmune reaction','Genetic predisposition','Bile reflux','Smoking','Dehydration','Structural abnormality','Reduced gastric motility'],
  fever:     ['Viral infection','Bacterial infection','Parasitic infection','Fungal infection','Inflammatory condition','Autoimmune disorder','Vaccination reaction','Heat exposure','Certain medications','Malignancy','Blood transfusion reaction','Unknown cause (idiopathic)','Insect or animal bite','Contaminated food or water','Travel to endemic region'],
  injuries:  ['Trauma or accident','Sports injury','Overuse or repetitive motion','Fall','Motor vehicle accident','Work-related injury','Improper technique during exercise','Lack of warm-up','Weak or fatigued muscles','Inadequate protective equipment','Environmental hazard','Burns from heat or chemicals','Bites or stings','Extreme temperature exposure','Sudden force or impact'],
  respiratory:['Viral infection','Bacterial infection','Allergens (pollen, dust, mould)','Air pollution and smoke','Tobacco smoking','Occupational exposure (dust, chemicals)','Genetic predisposition','Immune system dysfunction','Chronic inflammation','Acid reflux (GERD)','Exercise in cold air','Obesity','Sleep-related obstruction','Structural airway abnormality','Autoimmune condition'],
  head:      ['Tension and stress','Dehydration','Sleep disturbance','Hormonal fluctuation','Ear infection','Inner ear disorder','Viral or bacterial infection','Head injury or concussion','Neurological condition','Blood pressure changes','Temporomandibular joint dysfunction','Sinus congestion','Medication side effects','Genetic predisposition','Cervical spine dysfunction'],
  bones:     ['Age-related wear and tear','Autoimmune inflammation','Metabolic disorder','Calcium or vitamin D deficiency','Repetitive mechanical stress','Trauma or injury','Genetic predisposition','Hormonal imbalance','Sedentary lifestyle','Obesity','Previous joint injury','Infection','Crystal deposition (uric acid)','Poor posture','Occupational strain'],
  heart:     ['Atherosclerosis','Hypertension','High cholesterol','Diabetes mellitus','Obesity','Smoking','Sedentary lifestyle','Family history of heart disease','Arrhythmia','Valve defect','Infection or inflammation','Autoimmune disorder','Electrolyte imbalance','Stress','Congenital heart defect'],
  mental:    ['Genetic predisposition','Neurochemical imbalance','Childhood trauma or abuse','Chronic stress','Major life events','Social isolation','Substance use','Chronic physical illness','Sleep deprivation','Hormonal changes','Nutritional deficiency','Environmental factors','Personality traits','Learned thought patterns','Epigenetic factors'],
  urinary:   ['Bacterial infection','Kidney stone','Structural abnormality','Autoimmune inflammation','Hormonal changes','Enlarged prostate','Neurological dysfunction','Dehydration','Poor hygiene','Sexual activity','Catheter use','Diabetes mellitus','Pregnancy','Medications','Genetic predisposition'],
  womens:    ['Hormonal imbalance','Uterine or ovarian abnormality','Infection','Endometriosis','PCOS','Stress','Nutritional deficiency','Thyroid dysfunction','Autoimmune condition','Genetic factors','Pregnancy-related changes','Menopause','Structural pelvic abnormality','Medications','Immune system changes'],
  childrens: ['Viral infection','Bacterial infection','Immune system immaturity','Genetic or chromosomal abnormality','Nutritional deficiency','Environmental exposure','Developmental variation','Allergy','Birth complication','Premature birth','Maternal infection during pregnancy','Vaccine-preventable pathogen','Parasitic infection','Metabolic disorder','Psychosocial stress'],
};

const SYMPTOMS = {
  eyes:      ['Redness of the eye','Watery or sticky discharge','Itching or burning sensation','Blurred or reduced vision','Sensitivity to light (photophobia)','Swelling of the eyelid','Feeling of something in the eye','Pain or discomfort','Halos around lights','Double vision','Floaters or flashes','Eye fatigue','Crusting on eyelashes','Dry or gritty sensation','Abnormal eye movement'],
  teeth:     ['Tooth pain or aching','Sensitivity to hot or cold','Swollen or bleeding gums','Bad breath (halitosis)','Loose teeth','Visible holes or dark spots on teeth','Pain when biting or chewing','Swelling of the jaw or face','Mouth sores or ulcers','Dry mouth','Difficulty swallowing','White patches inside mouth','Jaw clicking or pain','Metallic taste','Facial pain'],
  skin:      ['Redness or inflammation','Itching (pruritus)','Rash or skin eruption','Blistering or weeping lesions','Scaling or flaking skin','Thickened or leathery skin','Pain or burning sensation','Swelling of affected area','Oozing or crusting','Skin discolouration','Hair loss in affected area','Nail changes','Warmth to touch','Open sores or ulcers','Dryness and cracking'],
  stomach:   ['Abdominal pain or cramping','Nausea','Vomiting','Diarrhoea','Constipation','Bloating and gas','Heartburn or acid reflux','Loss of appetite','Blood in stool','Unintentional weight loss','Jaundice (yellowing)','Belching','Feeling full quickly','Difficulty swallowing','Rectal pain or bleeding'],
  fever:     ['Elevated body temperature (>38°C)','Chills and shivering','Sweating','Headache','Muscle aches and fatigue','Loss of appetite','Nausea or vomiting','Sore throat','Cough','Runny or blocked nose','Rash','Joint pain','Swollen lymph nodes','Confusion or delirium','Sensitivity to light'],
  injuries:  ['Pain at the injury site','Swelling and bruising','Limited range of motion','Muscle weakness','Tenderness to touch','Deformity or abnormal position','Inability to bear weight','Numbness or tingling','Skin wound or bleeding','Instability of joint','Muscle spasm','Stiffness','Audible pop or crack at time of injury','Discolouration of skin','Blistering'],
  respiratory:['Shortness of breath (dyspnoea)','Persistent cough','Wheezing','Chest tightness or pain','Increased mucus or phlegm production','Noisy breathing (stridor)','Coughing up blood (haemoptysis)','Rapid breathing','Nasal congestion','Sore throat','Fever','Reduced oxygen saturation','Fatigue and weakness','Difficulty speaking in full sentences','Cyanosis (bluish lips or fingertips)'],
  head:      ['Headache (dull, throbbing, or sharp)','Dizziness or vertigo','Ear pain or pressure','Hearing loss or muffled hearing','Ringing in ears (tinnitus)','Nausea and vomiting','Sensitivity to light or sound','Facial pain or numbness','Visual disturbances','Neck stiffness','Nasal congestion','Jaw pain','Confusion or memory difficulty','Facial drooping','Balance problems'],
  bones:     ['Joint pain','Stiffness (especially morning stiffness)','Swelling around joints','Reduced range of motion','Bone pain','Muscle weakness','Tenderness to touch','Joint deformity','Cracking or grinding in joints (crepitus)','Fatigue','Difficulty walking or climbing stairs','Back pain','Nerve pain or tingling','Muscle wasting','Limping'],
  heart:     ['Chest pain or tightness','Shortness of breath','Palpitations (racing heart)','Swelling in legs or ankles','Fatigue and weakness','Dizziness or lightheadedness','Fainting','Irregular heartbeat','Coughing (especially at night)','Reduced exercise tolerance','Cold hands and feet','Cyanosis','Nausea','Excessive sweating','High blood pressure reading'],
  mental:    ['Persistent low mood or sadness','Excessive worry or fear','Difficulty sleeping','Changes in appetite or weight','Fatigue and loss of energy','Difficulty concentrating','Feelings of worthlessness or guilt','Social withdrawal','Irritability or mood swings','Hallucinations or delusions','Panic attacks','Flashbacks or nightmares','Compulsive behaviours','Suicidal thoughts','Memory problems'],
  urinary:   ['Painful or burning urination (dysuria)','Frequent urge to urinate','Blood in urine (haematuria)','Cloudy or foul-smelling urine','Pelvic or lower back pain','Incomplete bladder emptying','Urinary incontinence','Fever and chills (with infection)','Flank pain','Nausea and vomiting','Difficulty starting urination','Weak urine stream','Nocturia (night urination)','Proteinuria (foamy urine)','Swelling (oedema)'],
  womens:    ['Pelvic pain or cramping','Irregular or absent periods','Heavy or prolonged bleeding','Abnormal vaginal discharge','Vaginal itching or burning','Pain during intercourse','Bloating','Breast tenderness','Mood changes','Hot flushes','Vaginal dryness','Infertility','Nausea','Back pain','Pelvic pressure or fullness'],
  childrens: ['Fever','Irritability or unusual crying','Rash','Cough or runny nose','Vomiting or diarrhoea','Poor feeding','Lethargy or unusual sleepiness','Ear pulling','Swollen lymph nodes','Breathing difficulties','Redness or swelling','Developmental regression','Abdominal pain','Skin changes','Seizures'],
};

const REMEDIES = {
  eyes: [
    '🌡️ Soak a clean cloth in warm (not hot) water, wring out, and press gently over closed eyes for 10 minutes. Repeat 3× daily.',
    '💧 Mix ¼ tsp salt in 1 cup cooled boiled water. Use a sterile dropper to rinse each eye gently twice a day.',
    '🚫 Keep hands away from your face — touching eyes transfers bacteria and worsens infection.',
    '👓 Remove contact lenses immediately and switch to glasses until symptoms fully clear (usually 7–10 days).',
    '💊 Use preservative-free artificial tears every 2–3 hours to lubricate and flush irritants from eyes.',
    '📱 Follow the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds to relax eye muscles.',
    '😎 Wear wrap-around sunglasses outdoors — UV rays worsen most eye conditions and delay healing.',
    '🧼 Clean eyelid margins morning and night: dip a cotton pad in baby shampoo diluted 1:10 in water, wipe gently.',
    '💦 Run a humidifier at 40–50% humidity in your bedroom — dry air is a major trigger for eye irritation.',
    '🥤 Drink 8+ glasses of water daily — systemic hydration directly improves tear film quality.',
  ],
  teeth: [
    '🧂 Dissolve ½ tsp salt in 1 cup warm water. Swish vigorously for 60 seconds, 4× daily after meals. Spits out bacteria and reduces swelling.',
    '🌿 Dab 1–2 drops of clove oil onto a cotton ball and hold against the sore tooth for 5 minutes — natural eugenol numbs the area.',
    '🪥 Brush with a soft-bristled toothbrush at a 45° angle to the gumline for 2 full minutes, twice daily. Replace brush every 3 months.',
    '🦷 Floss once daily using 18 inches of floss, curving around each tooth in a C-shape. Never snap floss into gums.',
    '🧊 Apply a cold pack (ice in cloth) to the outside of the cheek for 15 minutes on, 15 off, to reduce dental swelling.',
    '🚫 Avoid drinks below 5°C or above 65°C if you have sensitivity — temperature extremes trigger sharp nerve pain.',
    '💧 Sip water every 15 minutes if you have dry mouth — saliva is your mouth\'s natural antibacterial defence.',
    '🫧 Use an alcohol-free antimicrobial mouthwash for 60 seconds before bed to kill bacteria missed by brushing.',
    '🍬 Chew xylitol gum for 5 minutes after each meal — xylitol actively prevents bacteria from sticking to teeth.',
    '🥛 Eat calcium-rich snacks (cheese, yoghurt, almonds) — calcium remineralises enamel and strengthens teeth.',
  ],
  skin: [
    '🧴 Apply a thick fragrance-free moisturiser (like CeraVe or Vaseline) within 3 minutes of getting out of the shower to lock in moisture.',
    '🧊 Wrap ice cubes in a thin cloth and apply to itchy area for 10 minutes — cold stops the itch-scratch cycle immediately.',
    '🚿 Shower in lukewarm water (under 38°C) for max 5 minutes. Hot water strips protective skin oils and worsens all skin conditions.',
    '🧼 Use only fragrance-free, pH-balanced soap or just water on affected areas. Rinse thoroughly — soap residue causes irritation.',
    '💊 Apply thin layer of 1% hydrocortisone cream to inflamed patch once daily for up to 7 days. Do not use on face or broken skin.',
    '✂️ Keep nails trimmed short and smooth — long nails cause deep scratch wounds that introduce bacteria and scar.',
    '👕 Switch to 100% cotton clothing and wash new clothes before wearing. Synthetic fabrics trap sweat and heat.',
    '📓 Keep a trigger diary: note food, detergent, stress, and weather each time symptoms flare — patterns appear within 2 weeks.',
    '🌿 Squeeze fresh aloe vera gel directly from a leaf onto minor rashes. Leave 20 minutes then rinse. Repeat 2× daily.',
    '🌬️ After bathing, pat (never rub) skin dry and let it air-dry completely before applying cream — friction damages the skin barrier.',
  ],
  stomach: [
    '🍽️ Eat 5–6 small meals (fist-sized portions) throughout the day instead of 3 large ones — reduces acid production and bloating.',
    '💧 Sip 200ml of water or oral rehydration solution every 15 minutes rather than large amounts at once to prevent vomiting.',
    '🚫 Eliminate fatty, fried, spicy, and acidic foods (citrus, coffee, tomatoes) for at least 48 hours during flare-ups.',
    '🫖 Brew fresh ginger tea: slice 1 inch of ginger, steep in boiling water 10 minutes, add honey. Drink slowly — relieves nausea in 20 min.',
    '🍌 Follow BRAT diet during diarrhoea: Bananas (morning), boiled Rice (lunch), unsweetened Applesauce, dry Toast. Easy on the gut.',
    '💊 Take an antacid tablet (calcium carbonate) within 30 minutes of heartburn starting — faster than liquid antacids for most people.',
    '⏰ Do not lie down for 2–3 hours after eating. If reflux wakes you at night, elevate bed head 15cm with blocks under legs.',
    '🔥 Place a warm (not hot) heating pad wrapped in cloth on abdomen for 15–20 minutes — relaxes intestinal muscle spasms.',
    '🌾 Add one tablespoon of psyllium husk to a glass of water daily for constipation — drink immediately before it thickens.',
    '☕ Reduce caffeine to 1 cup daily maximum and alcohol to zero during flare-ups — both trigger excess stomach acid.',
  ],
  fever: [
    '🛌 Lie down and rest completely. Physical activity raises core temperature further — even light movement extends fever duration.',
    '💧 Set a timer: drink 200ml of fluid every 30 minutes. Fever causes 500ml+ extra fluid loss per day through sweating.',
    '💊 Take paracetamol 500–1000mg (adults) every 4–6 hours OR ibuprofen 400mg every 6–8 hours with food. Never combine both at the same time.',
    '🧊 Soak a face cloth in cool (15°C) water, wring out, and place on forehead, neck, and wrists. Re-soak every 5 minutes.',
    '👕 Wear a single layer of light cotton clothing. Remove blankets if temperature is above 38.5°C — blankets trap heat.',
    '🌬️ Open a window or use a fan to maintain room temperature at 18–20°C. Do not use air conditioning below 18°C.',
    '🧂 Gargle with warm salt water (1 tsp in 1 cup) for 30 seconds every 2–3 hours to relieve a sore throat alongside the fever.',
    '💦 Use a saline nasal spray (2 sprays each nostril) every 4 hours to keep nasal passages moist and clear.',
    '🫧 Fill a bowl with near-boiling water, drape a towel over your head, lean over the bowl and inhale deeply for 10 minutes.',
    '🍲 Eat warm, easy-to-digest foods: plain chicken broth, rice porridge, or plain crackers — full meals increase metabolic heat.',
  ],
  injuries: [
    '🧊 RICE step 1 — Rest: Stop all activity immediately. Weight-bearing on a sprain within the first hour doubles healing time.',
    '🧊 RICE step 2 — Ice: Fill a bag with ice, wrap in a thin cloth (never ice directly on skin). Apply 20 minutes on, 20 off, for 48 hours.',
    '🩹 RICE step 3 — Compress: Wrap an elastic bandage snugly (not tight) from 5cm below to 5cm above the injury. Rewrap every 4 hours.',
    '🛋️ RICE step 4 — Elevate: Prop injured limb on 2–3 pillows so it is above heart level. Do this 3+ hours daily for the first 48 hours.',
    '💊 Take 400mg ibuprofen with food every 6–8 hours for the first 48–72 hours — reduces inflammation at the injury site.',
    '🚿 For cuts: hold under cool running water for 5–10 minutes to clean. Never use hydrogen peroxide — it damages healing tissue.',
    '🔥 For burns: cool immediately under cool running water for exactly 20 minutes. This is the single most important burn first aid step.',
    '🩺 After 48 hours of RICE, begin gentle range-of-motion exercises: 10 slow circles in each direction, 3× daily.',
    '🧴 Apply a thin layer of antiseptic cream (Savlon or Neosporin) to clean cuts before covering with a sterile non-stick dressing.',
    '💉 Check your tetanus vaccination status for any puncture wound — if not vaccinated in 10 years, seek a booster within 24 hours.',
  ],
  respiratory: [
    '🛌 Rest completely for the first 24–48 hours — your immune system diverts energy from muscles to fight infection when you rest.',
    '💧 Drink 300ml of warm fluid every hour: herbal tea, warm water with lemon, or clear chicken broth. Heat loosens thick mucus.',
    '🫧 Steam inhalation: pour boiling water into a large bowl, drape a towel over your head, inhale deeply through nose for 10 minutes. Do 3× daily.',
    '🌙 Run a cool-mist humidifier on your bedside table overnight — dry air thickens mucus and worsens coughing by morning.',
    '🍯 Mix 1 tbsp raw honey in warm water or tea. Sip slowly every 3–4 hours. Honey coats the throat and has proven antibacterial properties.',
    '🛏️ Sleep with 2 extra pillows under your head and shoulders — gravity keeps airways open and reduces post-nasal drip at night.',
    '💊 Use a saline nasal rinse (neti pot or bottle) twice daily: mix 1 tsp salt + ¼ tsp baking soda in 1 cup warm water. Flush each nostril.',
    '🚭 Stay 10+ metres from any tobacco smoke — even brief secondhand exposure inflames airways and undoes 48 hours of healing.',
    '💊 Take a non-drowsy antihistamine (cetirizine 10mg) if symptoms worsen in the morning — likely triggered by dust or pollen.',
    '🫁 Pursed-lip breathing: inhale slowly through nose (2 counts), exhale through puckered lips (4 counts). Repeat 10× to ease breathlessness.',
  ],
  head: [
    '🌑 At the first sign of headache: go to a dark, quiet room, lie down, and close your eyes for 15–20 minutes. Early rest shortens episodes.',
    '🧊 For tension headache: place an ice pack on forehead for 15 min. For neck tension: use a warm pack on the back of the neck instead.',
    '💧 Drink 500ml of cold water immediately — dehydration is the #1 cause of everyday headaches. Results within 30 minutes for most people.',
    '💊 Take paracetamol 1000mg or ibuprofen 400mg at the VERY first sign of pain — waiting until pain peaks makes medication 50% less effective.',
    '😮‍💨 Box breathing: inhale 4 counts, hold 4, exhale 4, hold 4. Repeat 6 cycles — lowers blood pressure and breaks tension headache cycle.',
    '⏰ Go to bed and wake up at the same time daily (±30 min) — irregular sleep is the most underrated headache trigger.',
    '👆 Massage technique: press thumbs firmly on the muscles at base of skull, hold 20 seconds. Then massage temples in slow circles for 2 minutes.',
    '💦 Use a saline nasal spray (2 sprays each nostril) and inhale steam for sinus headaches — draining sinuses relieves pressure within minutes.',
    '📓 Keep a headache diary: note time, food eaten, sleep, stress, weather. Within 2 weeks patterns reveal your personal triggers.',
    '🍬 For ear pressure: chew gum, yawn widely, or pinch nose and blow gently (Valsalva manoeuvre) to equalise middle ear pressure.',
  ],
  bones: [
    '🧊 First 48 hours: apply ice pack (wrapped in cloth) to inflamed joint for 20 minutes, every 2 hours. Cold reduces inflammation and pain.',
    '🔥 After 48 hours: switch to a warm pack for 15–20 minutes before exercise — heat relaxes stiff muscles and improves joint flexibility.',
    '💊 Take 400mg ibuprofen with food every 8 hours for the first 5 days — reduces joint inflammation at its source.',
    '🏊 Do 20 minutes of low-impact exercise daily: swimming, cycling, or walking in water. Movement lubricates joints and prevents stiffening.',
    '⚖️ Lose 1 kg of body weight to remove 4 kg of pressure from each knee. Even 5% weight loss produces measurable pain reduction.',
    '🥛 Eat 3 calcium-rich servings daily (1 glass milk = 300mg calcium). Pair with 15 min of sunlight for vitamin D to absorb it.',
    '🛋️ Elevate swollen joint on 2 pillows above heart level for 1 hour, 3× daily — gravity drains inflammatory fluid from the joint.',
    '🧴 Apply diclofenac gel (1%) to the painful joint and gently rub in for 60 seconds, twice daily — absorbed directly into joint tissue.',
    '🛏️ For back pain: sleep on your side with a pillow between knees to keep spine aligned. Avoid sleeping flat on your back.',
    '🧍 Check posture: ears over shoulders, shoulders over hips. Set a phone reminder every 30 minutes to sit up straight while working.',
  ],
  heart: [
    '🥗 Adopt the DASH diet this week: fill half your plate with vegetables and fruit, quarter with whole grains, quarter with lean protein.',
    '🚶 Walk for 30 minutes at a pace where you can talk but not sing — do this 5 days a week. Start with 10-minute sessions if needed.',
    '📊 Measure blood pressure at the same time each morning before coffee: sit quietly 5 minutes, then take 3 readings 1 minute apart.',
    '🧘 Try 4-7-8 breathing daily: inhale 4 counts, hold 7, exhale slowly over 8. Clinically proven to lower blood pressure within weeks.',
    '🍷 Reduce alcohol to maximum 2 units on any given day with 2–3 alcohol-free days per week. Each unit of alcohol raises blood pressure.',
    '🚭 Stop smoking today — every cigarette raises heart rate by 10–25 bpm for 30 minutes and damages arteries with each puff.',
    '🏃 Even 500g of weight loss per week (500 calorie daily deficit) measurably reduces cardiac workload within 2 weeks.',
    '☕ Switch to decaffeinated coffee or herbal tea — caffeine causes artery constriction and temporary blood pressure spikes.',
    '🛋️ Elevate both legs on a footstool for 30 minutes after sitting all day — reduces leg swelling and eases cardiac return.',
    '💊 Take all prescribed heart medications at the exact same time each day — set a phone alarm. Missing 2+ doses can trigger dangerous rhythms.',
  ],
  mental: [
    '⏰ Set the same alarm 7 days a week. Wake up at the same time even on weekends — a consistent circadian rhythm stabilises mood within 2 weeks.',
    '🏃 Walk or exercise for 30 minutes daily — produces endorphins and BDNF (brain growth factor) as effectively as mild antidepressants.',
    '😮‍💨 4-7-8 breathing for anxiety: inhale quietly through nose for 4 counts, hold breath for 7, exhale audibly for 8. Do 4 cycles.',
    '☕ Reduce caffeine to 1 cup before noon only — caffeine after 2pm disrupts sleep architecture and worsens anxiety next morning.',
    '📱 Call or message one person daily. Loneliness activates the same brain regions as physical pain — social contact is genuinely medicinal.',
    '📓 Write 3 specific things you are grateful for each night — not general things. Research shows this reduces depression symptoms in 4 weeks.',
    '🧠 When you notice a negative thought, write it down, then list 3 evidence points against it. Cognitive restructuring done daily rewires thought patterns.',
    '✅ Write 3 tiny achievable tasks each morning (e.g. "make bed, drink water, reply to 1 message"). Completing them builds momentum.',
    '☀️ Spend 20 minutes in natural outdoor light before 10am daily — regulates melatonin and serotonin production immediately.',
    '🎵 Create a calming bedtime routine: dim lights 1 hour before sleep, no screens, play calm music or white noise at low volume.',
  ],
  urinary: [
    '💧 Drink a large (500ml) glass of water immediately upon first symptoms — flushing bacteria before it colonises prevents escalation.',
    '⏰ Urinate every 2–3 hours regardless of urge — holding urine allows bacteria to multiply. Set phone reminders if needed.',
    '🧻 Always wipe strictly front to back after toileting — this single habit prevents the most common cause of UTIs in women.',
    '🚿 Urinate within 20 minutes of sexual activity — this flushes bacteria introduced during intercourse before it reaches the bladder.',
    '🍹 Drink 200ml of unsweetened pure cranberry juice twice daily — proanthocyanidins prevent bacteria from adhering to bladder walls.',
    '☕ Eliminate caffeine, alcohol, and carbonated drinks until symptoms resolve — all irritate the bladder lining and worsen urgency.',
    '🔥 Place a warm (not hot) heating pad wrapped in cloth on lower abdomen for 20 minutes, 3× daily — relaxes painful bladder spasms.',
    '🛁 Soak in a plain warm bath (no bubble bath, salts, or oils) for 15–20 minutes twice daily — relieves external burning and urgency.',
    '👙 Wear 100% cotton underwear and avoid tight synthetic clothing — moisture and heat from synthetics promote bacterial growth.',
    '⚖️ Maintain a healthy BMI — abdominal obesity compresses the bladder, increasing urgency, frequency, and infection risk.',
  ],
  womens: [
    '🔥 Place a heat patch (or hot water bottle wrapped in cloth) directly on lower abdomen for 20 minutes — as effective as ibuprofen for cramps.',
    '💊 Take 400mg ibuprofen at the very start of period pain (even before pain peaks) — prevents prostaglandins from triggering severe cramps.',
    '🧘 Do cat-cow pose for 2 minutes: on hands and knees, arch back up (cat) then dip it down (cow) slowly. Relieves pelvic tension instantly.',
    '💧 Reduce salt to under 1500mg daily 5 days before period — this alone reduces bloating and breast tenderness significantly.',
    '🧊 For breast tenderness: wear a soft, supportive sports bra 24/7. Apply a cool cloth compress for 10 minutes when tender.',
    '🩺 For vaginal thrush: apply plain unsweetened live probiotic yoghurt externally for cooling relief. Do not douche — disrupts pH.',
    '🚿 Wash intimate areas with plain warm water only or a pH 3.8–4.5 intimate wash. Soap destroys the protective lactobacillus environment.',
    '📅 Track your cycle with a period app for 3 months — identifying your pattern helps predict and prepare for symptoms 3–5 days in advance.',
    '🚴 Do 20–30 minutes of light aerobic exercise (cycling, swimming) 3–4× weekly — reduces period pain by up to 50% over 3 months.',
    '🫖 Drink 2 cups of chamomile or raspberry leaf tea daily in the week before your period — contains anti-inflammatory compounds.',
  ],
  childrens: [
    '💧 For a sick child: offer 50–100ml of fluid every 15–20 minutes (not all at once). Use an oral syringe for infants if needed.',
    '💦 Run a cool-mist humidifier 30–50cm from the child\'s bed at night — loosens mucus so it drains rather than causing congestion.',
    '🧴 For itchy rash: apply calamine lotion with a cotton pad gently in one direction — do not rub. Reapply every 4–6 hours.',
    '💊 Dose paracetamol by weight (15mg/kg every 4–6 hours, max 4 doses/day). Always use the oral syringe provided — spoons are inaccurate.',
    '🍑 Prevent nappy rash: at each change, pat completely dry, apply thick zinc oxide paste barrier cream before rash appears.',
    '🥶 For teething: wet a clean face cloth, twist it tightly, freeze for 30 minutes. Give to baby to chew — safer than teething rings.',
    '👕 During fever: remove all but one light cotton layer. Do not wrap in blankets — wrapping raises temperature further.',
    '🍼 For reflux baby: hold upright for 20–30 minutes after every feed. Raise one end of cot mattress 15° using a rolled towel underneath.',
    '🥣 For vomiting child: wait 15 minutes after vomiting, then offer 5ml (1 teaspoon) of water every 5 minutes. Increase slowly over 1 hour.',
    '💉 Keep child\'s vaccine record updated — note each vaccine date and brand. Bring this record to every doctor visit.',
  ],
};

const DOCTOR_IF = {
  eyes:      ['Vision is significantly blurred or suddenly lost','Severe eye pain or injury occurred','Symptoms persist for more than 5–7 days','Eye discharge is thick or greenish yellow','A child under 1 year is affected','You have diabetes or a known immune disorder'],
  teeth:     ['Tooth or jaw pain is severe and persistent','There is visible swelling of the face or neck','You have a high fever alongside dental pain','A tooth is knocked out (see dentist within 30 minutes)','You notice red or white patches in your mouth','Bleeding gums do not improve after 2 weeks of good hygiene'],
  skin:      ['Skin becomes infected (increasing warmth, pus, red streaking)','Rash spreads rapidly or covers a large body area','You develop a high fever alongside the rash','Symptoms do not improve after 2–3 weeks of home treatment','A mole changes shape, size, or colour','You have difficulty breathing or swallowing (anaphylaxis risk)'],
  stomach:   ['Blood in vomit or stool (red or black)','Severe abdominal pain that does not ease','Signs of dehydration: no urine output for 8+ hours, extreme thirst, confusion','Vomiting persists for more than 24 hours (or 12 hours in a child)','Unintentional weight loss','Jaundice (yellow skin or eyes)'],
  fever:     ['Fever above 39.5°C (103°F) in adults or any fever in infants under 3 months','Fever lasts more than 3 days without improvement','Stiff neck, sensitivity to light, or confusion develop','Severe difficulty breathing','Signs of dehydration appear','A seizure occurs'],
  injuries:  ['Severe pain, significant swelling, or visible deformity (possible fracture)','Wound does not stop bleeding after 10 minutes of direct pressure','Signs of infection: increasing redness, warmth, pus, red streaking','A burn is larger than the palm of your hand or affects the face, hands, or genitals','Numbness, tingling, or inability to move below the injury','A child is injured; always seek medical assessment'],
  respiratory:['Severe difficulty breathing or cyanosis (blue lips/fingertips)','Coughing up blood or blood-streaked phlegm','Symptoms do not improve after 7–10 days','Chest pain accompanies breathing difficulty','High fever (above 39°C) with respiratory symptoms','A child under 2 develops significant breathing difficulty'],
  head:      ['Sudden, very severe "thunderclap" headache (worst of your life)','Headache with stiff neck, fever, or rash','Neurological symptoms: weakness, speech difficulty, vision loss','Ear pain with high fever or discharge from the ear','Dizziness so severe it prevents standing or walking','Symptoms do not improve after 2–3 weeks'],
  bones:     ['You cannot bear weight or use the affected limb','Severe swelling or deformity is present','Joint is hot, red, and swollen (possible infection or gout)','Symptoms do not improve after 2–3 weeks of home treatment','Nerve symptoms: numbness, tingling, or weakness','You have a history of cancer (rule out bone metastasis)'],
  heart:     ['Chest pain, tightness, or pressure — call emergency services immediately','Sudden severe shortness of breath','Palpitations with dizziness or fainting','Blood pressure reading consistently above 140/90 mmHg','Unexplained swelling in both legs','Any cardiac symptom in a person with known heart disease'],
  mental:    ['You have thoughts of self-harm or suicide — seek help immediately','Symptoms significantly interfere with work, relationships, or daily life','Psychotic symptoms develop (hallucinations, delusions)','Symptoms have persisted for more than 2 weeks despite self-care','You are using substances to cope','A child or teenager is affected'],
  urinary:   ['High fever with back pain and chills (possible kidney infection)','Blood in urine','Severe pain in the flank, back, or groin','Symptoms do not resolve within 2–3 days of home treatment','You are pregnant and have UTI symptoms','Men with any urinary tract symptoms should always see a doctor'],
  womens:    ['Heavy bleeding soaking more than one pad per hour','Severe pelvic pain','Fever with vaginal discharge (possible PID)','Periods absent for more than 3 months','Symptoms of pregnancy complication (severe vomiting, bleeding)','Symptoms do not resolve after home treatment'],
  childrens: ['Infant under 3 months has any fever','Child has a febrile seizure','Signs of severe dehydration (no tears, very dry mouth, no urine for 8+ hours)','Breathing is rapid, laboured, or making a grunting sound','Rash is purple or does not fade when pressed (meningococcal sign)','Child is unusually difficult to rouse or very unresponsive'],
};

// ─── Helper utilities ─────────────────────────────────────────────────────────

function pick(arr, n = 4) {
  const shuffled = [...arr].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, n);
}

function slugify(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function catForKey(key) {
  const map = {
    eyes: 'Eyes', teeth: 'Teeth & Mouth', skin: 'Skin',
    stomach: 'Stomach', fever: 'Fever & Flu', injuries: 'Injuries',
    respiratory: 'Respiratory', head: 'Head & Ear', bones: 'Bones & Joints',
    heart: 'Heart & Blood', mental: 'Mental Health', urinary: 'Urinary',
    womens: "Women's Health", childrens: "Children's Health",
  };
  return map[key] || key;
}

// Short intro templates
function makeIntro(name, catKey) {
  const intros = [
    `${name} is a common condition affecting the ${catForKey(catKey).toLowerCase()} system, often causing discomfort that can be managed at home.`,
    `${name} refers to inflammation, dysfunction, or infection of related structures that requires appropriate care to resolve.`,
    `${name} is a medical condition characterised by specific signs and symptoms that range from mild to severe depending on the cause.`,
    `${name} is a health condition that affects many people and can often be relieved with simple home measures alongside medical guidance.`,
    `${name} describes a clinical condition in which the body's normal functioning is disrupted, resulting in characteristic symptoms.`,
  ];
  return intros[Math.floor(Math.random() * intros.length)];
}

// ─── Build disease list ────────────────────────────────────────────────────────

const diseases = [];

for (const [catKey, names] of Object.entries(SEED)) {
  const causesBank   = CAUSES[catKey]   || CAUSES.fever;
  const symptomsBank = SYMPTOMS[catKey] || SYMPTOMS.fever;
  const remediesBank = REMEDIES[catKey] || REMEDIES.fever;
  const doctorBank   = DOCTOR_IF[catKey]|| DOCTOR_IF.fever;

  for (const name of names) {
    diseases.push({
      id:          slugify(name),
      category:    catForKey(catKey),
      category_id: catKey,
      name,
      intro:       makeIntro(name, catKey),
      causes:      pick(causesBank, 4 + Math.floor(Math.random() * 2)),
      symptoms:    pick(symptomsBank, 4 + Math.floor(Math.random() * 2)),
      home_remedies: pick(remediesBank, 4 + Math.floor(Math.random() * 2)),
      doctor_visit_if: pick(doctorBank, 3),
      image: null,
    });
  }
}

// ─── Write output ─────────────────────────────────────────────────────────────

const outDir  = path.join(__dirname, '..', 'assets');
const outFile = path.join(outDir, 'diseases.json');

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const output = {
  generated:     new Date().toISOString(),
  total:         diseases.length,
  categories:    [...new Set(diseases.map(d => d.category))],
  diseases,
};

fs.writeFileSync(outFile, JSON.stringify(output, null, 2), 'utf8');

console.log(`✅  diseases.json written to: ${outFile}`);
console.log(`📊  Total diseases: ${diseases.length}`);
console.log(`🗂   Categories (${output.categories.length}): ${output.categories.join(', ')}`);

const byCat = {};
for (const d of diseases) byCat[d.category] = (byCat[d.category] || 0) + 1;
for (const [cat, count] of Object.entries(byCat)) {
  console.log(`     ${cat.padEnd(22)} ${count}`);
}
